FROM landoop/fast-data-dev:latest
MAINTAINER Marios Andreopoulos <marios@landoop.com>

RUN apk add --no-cache go git
ADD nmea-sample /

ENV GOPATH=/opt/go PATH=$PATH:/opt/go/bin
ADD main.go /opt/go/src/landoop/ais-mqtt/
RUN cd /opt/go/src/landoop/ais-mqtt/ \
    && go get -v \
    && go build -v
