FROM landoop/fast-data-dev:latest
MAINTAINER Marios Andreopoulos <marios@landoop.com>

RUN apk add --no-cache go musl-dev git

ENV GOPATH=/opt/go PATH=$PATH:/opt/go/bin
ADD ais-mqtt /opt/go/src/landoop/ais-mqtt
RUN cd /opt/go/src/landoop/ais-mqtt/ \
    && go get -v \
    && go build -v
